# Generated by Django 4.0.3 on 2022-04-06 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_url_short_url_url_owner_url_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=50)),
                ('os', models.CharField(max_length=50)),
                ('browser', models.CharField(max_length=50)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.url')),
            ],
        ),
    ]
